require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::ChannelsController do

  # This should return the minimal set of attributes required to create a valid
  # Admin::Channel. As you add validations to Admin::Channel, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Admin::ChannelsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all admin_channels as @admin_channels" do
      channel = Admin::Channel.create! valid_attributes
      get :index, {}, valid_session
      assigns(:admin_channels).should eq([channel])
    end
  end

  describe "GET show" do
    it "assigns the requested admin_channel as @admin_channel" do
      channel = Admin::Channel.create! valid_attributes
      get :show, {:id => channel.to_param}, valid_session
      assigns(:admin_channel).should eq(channel)
    end
  end

  describe "GET new" do
    it "assigns a new admin_channel as @admin_channel" do
      get :new, {}, valid_session
      assigns(:admin_channel).should be_a_new(Admin::Channel)
    end
  end

  describe "GET edit" do
    it "assigns the requested admin_channel as @admin_channel" do
      channel = Admin::Channel.create! valid_attributes
      get :edit, {:id => channel.to_param}, valid_session
      assigns(:admin_channel).should eq(channel)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Admin::Channel" do
        expect {
          post :create, {:admin_channel => valid_attributes}, valid_session
        }.to change(Admin::Channel, :count).by(1)
      end

      it "assigns a newly created admin_channel as @admin_channel" do
        post :create, {:admin_channel => valid_attributes}, valid_session
        assigns(:admin_channel).should be_a(Admin::Channel)
        assigns(:admin_channel).should be_persisted
      end

      it "redirects to the created admin_channel" do
        post :create, {:admin_channel => valid_attributes}, valid_session
        response.should redirect_to(Admin::Channel.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved admin_channel as @admin_channel" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Channel.any_instance.stub(:save).and_return(false)
        post :create, {:admin_channel => { "user" => "invalid value" }}, valid_session
        assigns(:admin_channel).should be_a_new(Admin::Channel)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Channel.any_instance.stub(:save).and_return(false)
        post :create, {:admin_channel => { "user" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested admin_channel" do
        channel = Admin::Channel.create! valid_attributes
        # Assuming there are no other admin_channels in the database, this
        # specifies that the Admin::Channel created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Admin::Channel.any_instance.should_receive(:update).with({ "user" => "" })
        put :update, {:id => channel.to_param, :admin_channel => { "user" => "" }}, valid_session
      end

      it "assigns the requested admin_channel as @admin_channel" do
        channel = Admin::Channel.create! valid_attributes
        put :update, {:id => channel.to_param, :admin_channel => valid_attributes}, valid_session
        assigns(:admin_channel).should eq(channel)
      end

      it "redirects to the admin_channel" do
        channel = Admin::Channel.create! valid_attributes
        put :update, {:id => channel.to_param, :admin_channel => valid_attributes}, valid_session
        response.should redirect_to(channel)
      end
    end

    describe "with invalid params" do
      it "assigns the admin_channel as @admin_channel" do
        channel = Admin::Channel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Channel.any_instance.stub(:save).and_return(false)
        put :update, {:id => channel.to_param, :admin_channel => { "user" => "invalid value" }}, valid_session
        assigns(:admin_channel).should eq(channel)
      end

      it "re-renders the 'edit' template" do
        channel = Admin::Channel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Channel.any_instance.stub(:save).and_return(false)
        put :update, {:id => channel.to_param, :admin_channel => { "user" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested admin_channel" do
      channel = Admin::Channel.create! valid_attributes
      expect {
        delete :destroy, {:id => channel.to_param}, valid_session
      }.to change(Admin::Channel, :count).by(-1)
    end

    it "redirects to the admin_channels list" do
      channel = Admin::Channel.create! valid_attributes
      delete :destroy, {:id => channel.to_param}, valid_session
      response.should redirect_to(admin_channels_url)
    end
  end

end
