base: &base
  adapter: mysql2
  encoding: utf8
  reconnect: true
  wait_timeout: 600
  pool: 25
  username: root
  password: password
  host: 127.0.0.1
  port: 3306
  database: raincms

development:
  <<: *base

test:
  <<: *base

production:
  <<: *base